include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_this: false
    omit_local_variable_types: false
    constant_identifier_names: false

analyzer:
  errors:
    unsafe_html: ignore
