name: cookza
description: Organize and share your favorite recipes.

version: 0.0.6+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.4
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.7.2
  share: ^2.0.1
  http: ^0.13.1
  path: ^1.8.0
  path_provider: ^2.0.1
  json_annotation: ^4.0.0
  introduction_screen: ^2.0.0
  get_it: ^6.0.0
  file_picker: ^3.0.0
  pdf: ^3.1.0
  barcode_widget: ^2.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_ml_vision: 
    git:
      url: git://github.com/alex0711/flutterfire.git
      path: packages/firebase_ml_vision
  package_info: '^2.0.0'
  url_launcher: ^6.0.2
  camera: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  mockito: ^5.0.0
  pedantic: ^1.11.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
