name: cookza
description: Organize and share your favorite recipes.

version: 0.0.27+1

publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.4
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.0
  share_plus: ^2.1.2
  http: ^0.13.1
  path: ^1.8.0
  path_provider: ^2.0.1
  json_annotation: ^4.0.0
  introduction_screen: ^2.0.0
  get_it: ^7.1.3
  file_picker: ^4.0.0
  pdf: ^3.1.0
  barcode_widget: ^2.0.1
  firebase_auth: ^3.0.0
  cloud_firestore: ^2.1.0
  firebase_storage: ^10.0.1
  google_ml_kit: ^0.7.0
  package_info_plus: ^1.0.1
  url_launcher: ^6.0.2
  camera: ^0.8.0
  photo_view: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  json_serializable: ^4.0.2
  mockito: ^5.0.0
  pedantic: ^1.11.0
  fake_cloud_firestore: ^1.1.0
  firebase_storage_mocks: ^0.5.0
  flutter_launcher_icons: ^0.9.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
