name: cookza
description: Organize and share your favorite recipes.

version: 0.0.39+1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  font_awesome_flutter: ^10.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.4
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.0
  share_plus: ^6.3.0
  http: ^0.13.1
  path: ^1.8.0
  path_provider: ^2.0.1
  json_annotation: ^4.6.0
  introduction_screen: ^3.0.0
  get_it: ^7.1.3
  file_picker: ^5.2.2
  pdf: ^3.8.0
  barcode_widget: ^2.0.1
  collection: ^1.17.0
  uuid: ^3.0.6

  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6

  google_mlkit_barcode_scanning: ^0.5.0
  google_mlkit_text_recognition: ^0.5.0
  
  package_info_plus: ^3.0.2
  url_launcher: ^6.0.2
  camera: ^0.10.0
  photo_view: ^0.14.0
  logging: ^1.0.1
  week_of_year: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  json_serializable: ^6.0.0
  mockito: ^5.0.16
  fake_cloud_firestore: ^2.0.1
  firebase_storage_mocks: ^0.6.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
