name: cookza
description: Organize and share your favorite recipes.

version: 0.0.33+1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  font_awesome_flutter: ^10.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.4
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.0
  share_plus: ^4.0.1
  http: ^0.13.1
  path: ^1.8.0
  path_provider: ^2.0.1
  json_annotation: ^4.3.0
  introduction_screen: ^3.0.0
  get_it: ^7.1.3
  file_picker: ^4.0.0
  pdf: ^3.1.0
  barcode_widget: ^2.0.1
  collection: ^1.16.0

  firebase_core: ^1.16.0
  firebase_auth: ^3.0.0
  cloud_firestore: ^3.1.4
  firebase_storage: ^10.0.1

  google_ml_kit: ^0.11.0
  package_info_plus: ^1.0.1
  url_launcher: ^6.0.2
  camera: ^0.9.0
  photo_view: ^0.13.0
  logging: ^1.0.1
  week_of_year: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  json_serializable: ^6.0.0
  mockito: ^5.0.16
  fake_cloud_firestore: ^1.2.0
  firebase_storage_mocks: ^0.5.0
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
