name: cookza
description: Organize and share your favorite recipes.

version: 0.0.43+1

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  font_awesome_flutter: ^10.0.0
  intl: ^0.19.0
  shared_preferences: ^2.3.5
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.0.1
  share_plus: ^10.1.4
  http: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.0.1
  json_annotation: ^4.9.0
  introduction_screen: ^3.0.0
  get_it: ^8.0.3
  file_picker: ^8.1.7
  pdf: ^3.8.0
  barcode_widget: ^2.0.1
  collection: ^1.19.0
  uuid: ^4.2.2

  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0

  google_mlkit_barcode_scanning: ^0.13.0
  google_mlkit_text_recognition: ^0.14.0
  
  package_info_plus: ^8.1.3
  url_launcher: ^6.0.2
  camera: ^0.11.0+2
  photo_view: ^0.15.0
  logging: ^1.0.1
  week_of_year: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  json_serializable: ^6.0.0
  mockito: ^5.0.16
  fake_cloud_firestore: ^3.1.0
  firebase_storage_mocks: ^0.7.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
