name: Format

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: dartfmt ./ --set-exit-if-changed
