name: Format

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: dart format ./ --set-exit-if-changed
