name: Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  package-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter test
