name: Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  package-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter test
